---
Name: inpagegallery-config
---
Page:
  extensions:
    - Cwchong\SilverstripeEditorgallery\extensions\InPageGalleryExtension
    - Cwchong\SilverstripeEditorgallery\extensions\InPageTimelineExtension
