---
Name: inpagegallery-route
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'inpagegallery//$Action/$ID/$Name': 'Cwchong\SilverstripeEditorgallery\controllers\InPageGalleryController'
#    'inpagetimeline//$Action/$ID/$Name': InPageTimelineController